// <auto-generated />
using System;
using AracKiralamaVeSatisOtomasyonu.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AracKiralamaVeSatisOtomasyonu.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250501171119_m2")]
    partial class m2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AracKiralamaVeSatisOtomasyonu.Models.Arac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("Kilometre")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MevcutDurum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanzimanTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakitTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Arac");
                });

            modelBuilder.Entity("AracKiralamaVeSatisOtomasyonu.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategori");

                    b.HasData(
                        new
                        {
                            KategoriId = 1,
                            KategoriAdi = "Sedan"
                        },
                        new
                        {
                            KategoriId = 2,
                            KategoriAdi = "SUV"
                        },
                        new
                        {
                            KategoriId = 3,
                            KategoriAdi = "Hatchback"
                        },
                        new
                        {
                            KategoriId = 4,
                            KategoriAdi = "Minivan"
                        });
                });

            modelBuilder.Entity("AracKiralamaVeSatisOtomasyonu.Models.Kiralama", b =>
                {
                    b.Property<int>("KiralamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KiralamaId"));

                    b.Property<string>("AracId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AracId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GunlukUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.HasKey("KiralamaId");

                    b.HasIndex("AracId1");

                    b.HasIndex("MusteriId");

                    b.ToTable("Kiralama");
                });

            modelBuilder.Entity("AracKiralamaVeSatisOtomasyonu.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MusteriId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.ToTable("Musteri");
                });

            modelBuilder.Entity("AracKiralamaVeSatisOtomasyonu.Models.Satis", b =>
                {
                    b.Property<int>("SatisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SatisId"));

                    b.Property<int>("AracId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<string>("OdemeTipi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SatisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("SatisId");

                    b.HasIndex("AracId");

                    b.HasIndex("MusteriId");

                    b.ToTable("Satis");
                });

            modelBuilder.Entity("AracKiralamaVeSatisOtomasyonu.Models.Arac", b =>
                {
                    b.HasOne("AracKiralamaVeSatisOtomasyonu.Models.Kategori", "Kategori")
                        .WithMany("Araclar")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("AracKiralamaVeSatisOtomasyonu.Models.Kiralama", b =>
                {
                    b.HasOne("AracKiralamaVeSatisOtomasyonu.Models.Arac", "Arac")
                        .WithMany("Kiralamalar")
                        .HasForeignKey("AracId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AracKiralamaVeSatisOtomasyonu.Models.Musteri", "Musteri")
                        .WithMany("Kiralamalar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("AracKiralamaVeSatisOtomasyonu.Models.Satis", b =>
                {
                    b.HasOne("AracKiralamaVeSatisOtomasyonu.Models.Arac", "Arac")
                        .WithMany("Satislar")
                        .HasForeignKey("AracId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AracKiralamaVeSatisOtomasyonu.Models.Musteri", "Musteri")
                        .WithMany("Satislar")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arac");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("AracKiralamaVeSatisOtomasyonu.Models.Arac", b =>
                {
                    b.Navigation("Kiralamalar");

                    b.Navigation("Satislar");
                });

            modelBuilder.Entity("AracKiralamaVeSatisOtomasyonu.Models.Kategori", b =>
                {
                    b.Navigation("Araclar");
                });

            modelBuilder.Entity("AracKiralamaVeSatisOtomasyonu.Models.Musteri", b =>
                {
                    b.Navigation("Kiralamalar");

                    b.Navigation("Satislar");
                });
#pragma warning restore 612, 618
        }
    }
}
